SET TERM ^ ;

CREATE TRIGGER AI_CREDIT FOR CREDIT 
AFTER INSERT
AS 
BEGIN 
    UPDATE ACCOUNT
       SET CREDIT_AVAILABLE = COALESCE(CREDIT_AVAILABLE,0) + COALESCE(NEW.CREDIT_PURCHASED,0)
     WHERE ACCOUNT_ID = NEW.ACCOUNT_ID;
END^

SET TERM ; ^


