SET TERM ^ ;

CREATE PROCEDURE P_GET_ITEMS
RETURNS 
 ( R_ITEM_ID INTEGER,
   R_ITEM_NAME VARCHAR(50),
   R_ITEM_DESCRIPTION VARCHAR(100))
AS  
BEGIN
  FOR 
        SELECT ITEM_ID,
               ITEM_NAME,
               ITEM_DESCRIPTION
          FROM ITEM
         WHERE COALESCE(ACTIVE,FALSE) = TRUE
      ORDER BY ITEM_NAME
          INTO :R_ITEM_ID,
               :R_ITEM_NAME,
               :R_ITEM_DESCRIPTION
  DO
  SUSPEND;
END^

SET TERM ; ^
