SET TERM ^ ;

CREATE PROCEDURE P_GET_SUPPLIERS 
RETURNS 
 ( R_SUPPLIER_ID INTEGER,
   R_SUPPLIER_NAME VARCHAR(50),
   R_SUPPLIER_ADDRESS VARCHAR(100) )
AS 
BEGIN
  FOR 
    SELECT SUPPLIER_ID,
           SUPPLIER_NAME,
           SUPPLIER_ADDRESS
      FROM SUPPLIER
  ORDER BY SUPPLIER_NAME
      INTO :R_SUPPLIER_ID,
           :R_SUPPLIER_NAME,
           :R_SUPPLIER_ADDRESS
  DO 
  SUSPEND;
END^

SET TERM ; ^
