SET TERM ^ ;

CREATE PROCEDURE P_GET_EXPENSE_TYPES 
RETURNS 
 ( R_EXPENSE_ID INTEGER,
   R_EXPENSE_NAME VARCHAR(50),
   R_EXPENSE_DESCRIPTION VARCHAR(100))
AS  
BEGIN
  FOR 
        SELECT EXPENSE_ID,
               EXPENSE_NAME,
               EXPENSE_DESCRIPTION
          FROM T_EXPENSETYPE
      ORDER BY EXPENSE_NAME
          INTO :R_EXPENSE_ID,
               :R_EXPENSE_NAME,
               :R_EXPENSE_DESCRIPTION
  DO
  SUSPEND;
END^

SET TERM ; ^
