SET TERM ^ ;

CREATE PROCEDURE P_GET_ASSIGNED_RIGHTS
(
    P_ROLE_CODE CHAR(3)
)
RETURNS 
 ( R_RIGHT_CODE VARCHAR(15),
   R_RIGHT_NAME VARCHAR(100),
   R_ASSIGNED BOOLEAN )
AS 
BEGIN
  FOR 
    SELECT R.RIGHT_CODE,
           R.RIGHT_NAME,
           (CASE WHEN L.ROLE_CODE IS NULL THEN FALSE ELSE TRUE END)
      FROM SYSRIGHT R
 LEFT JOIN SYSROLERIGHT L
        ON L.RIGHT_CODE = R.RIGHT_CODE
       AND L.ROLE_CODE = :P_ROLE_CODE
  ORDER BY R.RIGHT_NAME
      INTO :R_RIGHT_CODE,
           :R_RIGHT_NAME,
           :R_ASSIGNED
  DO 
  SUSPEND;
END^

SET TERM ; ^
