UPDATE ITEM SET ACTIVE = TRUE;

INSERT INTO SYSRIGHT VALUES ('ADD_USER','Add system user',null);

INSERT INTO SYSROLE VALUES ('ADM','Administrator',null);

INSERT INTO SYSROLERIGHT VALUES ('ADM','ADD_USER');

INSERT INTO SYSUSER (USERNAME, PASSKEY, ROLE_CODE) VALUES ('ADMIN','admin123','ADM');



